load("@crates//:defs.bzl", "all_crate_deps")
load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")
exports_files(["Cargo.toml"])
rust_library(
    name = "workflow_runstore_postgres",
    srcs = glob(["src/**/*.rs"]),
    compile_data = ["src/schema.sql"],
    crate_root = "src/lib.rs",
    edition = "2024",
    deps = ["//crates/workflow-runstore:workflow_runstore", "//crates/workflow-runstore-sqlite:workflow_runstore_sqlite", "//crates/workflow-worker:workflow_worker", "//crates/workflow-kernel:workflow_kernel", "//crates/workflow-artifacts:workflow_artifacts", "//crates/workflow-effects:workflow_effects"] + all_crate_deps(normal = True),
    proc_macro_deps = all_crate_deps(proc_macro = True),
    visibility = ["//visibility:public"],
)
rust_test(
    name = "tests",
    size = "small",
    crate = ":workflow_runstore_postgres",
    data = ["//:fixtures"],
    deps = ["//crates/workflow-runtime:workflow_runtime", "//crates/workflow-builtin-capabilities:workflow_builtin_capabilities"] + all_crate_deps(normal_dev = True),
)
