[package]
name = "workflow-runstore-postgres"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
workflow-templates = { path = "../workflow-templates" }
workflow-credentials = { path = "../workflow-credentials" }
workflow-ir = { path = "../workflow-ir" }
workflow-validator = { path = "../workflow-validator" }
postgres = "0.19.14"
getrandom = "0.4.3"
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
workflow-runstore = { path = "../workflow-runstore" }
workflow-runstore-sqlite = { path = "../workflow-runstore-sqlite" }
workflow-worker = { path = "../workflow-worker" }
workflow-kernel = { path = "../workflow-kernel" }
workflow-artifacts = { path = "../workflow-artifacts" }
workflow-effects = { path = "../workflow-effects" }

[dev-dependencies]
workflow-builtin-capabilities = { path = "../workflow-builtin-capabilities" }
workflow-runtime = { path = "../workflow-runtime" }
