[package]
name = "workflow-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
workflow-runtime = { path = "../workflow-runtime" }
workflow-runstore = { path = "../workflow-runstore" }
workflow-runstore-sqlite = { path = "../workflow-runstore-sqlite" }
workflow-kernel = { path = "../workflow-kernel" }
workflow-worker = { path = "../workflow-worker" }
workflow-builtin-capabilities = { path = "../workflow-builtin-capabilities" }
serde.workspace = true
serde_json.workspace = true
workflow-ir = { path = "../workflow-ir" }
workflow-validator = { path = "../workflow-validator" }

workflow-definitions = { path = "../workflow-definitions" }
workflow-registry-sqlite = { path = "../workflow-registry-sqlite" }

workflow-artifacts = { path = "../workflow-artifacts" }
workflow-artifact-local = { path = "../workflow-artifact-local" }

[[bin]]
name = "workflow"
path = "src/main.rs"
