[package]
name = "workflow-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
workflow-ir = { path = "../workflow-ir" }
workflow-validator = { path = "../workflow-validator" }

[[bin]]
name = "workflow"
path = "src/main.rs"
