[package]
name = "workflow-runstore-sqlite"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
workflow-gates = { path = "../workflow-gates" }
rusqlite.workspace = true
serde.workspace = true
workflow-runstore = { path = "../workflow-runstore" }
workflow-kernel = { path = "../workflow-kernel" }
workflow-worker = { path = "../workflow-worker" }
workflow-artifacts = { path = "../workflow-artifacts" }

[dev-dependencies]
workflow-artifact-local = { path = "../workflow-artifact-local" }
workflow-builtin-capabilities = { path = "../workflow-builtin-capabilities" }
