[package]
name = "workflow-kernel"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
workflow-effects = { path = "../workflow-effects" }
workflow-models = { path = "../workflow-models" }
workflow-artifacts = { path = "../workflow-artifacts" }
workflow-gates = { path = "../workflow-gates" }
serde.workspace = true
serde_json.workspace = true
schemars.workspace = true
workflow-ir = { path = "../workflow-ir" }
workflow-validator = { path = "../workflow-validator" }
workflow-worker = { path = "../workflow-worker" }
