[package]
name = "workflow-definitions"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
schemars.workspace = true
workflow-ir = { path = "../workflow-ir" }
workflow-validator = { path = "../workflow-validator" }
