load("@crates//:defs.bzl", "all_crate_deps")
load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")
exports_files(["Cargo.toml"])
rust_library(
    name = "workflow_effect_http",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    edition = "2024",
    deps = ["//crates/workflow-credentials:workflow_credentials", "//crates/workflow-effects:workflow_effects", "//crates/workflow-ir:workflow_ir", "//crates/workflow-worker:workflow_worker", "//crates/workflow-workspace-local:workflow_workspace_local"] + all_crate_deps(normal = True),
    proc_macro_deps = all_crate_deps(proc_macro = True),
    visibility = ["//visibility:public"],
)
rust_test(name = "tests", size = "small", crate = ":workflow_effect_http", data = ["//:fixtures"])
